/**
 * Where the server keeps files. Two things only: the organization's knowledge
 * base documents, which live here, and an upload on its way to a device, which
 * waits here until its message is sent and is then removed — projects and their
 * files live on devices. A local directory does for one server; replicas need a
 * store they share, hence the S3-compatible option. Chosen by configuration; the
 * rest of the server only sees `put`, `get` and `remove`.
 */
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { DeleteObjectCommand, GetObjectCommand, PutObjectCommand, S3Client } from "@aws-sdk/client-s3";
import type { Config } from "./config.ts";

export interface Storage {
  put(key: string, body: Buffer, contentType?: string | null): Promise<void>;
  get(key: string): Promise<Buffer>;
  remove(key: string): Promise<void>;
}

/** Keys are generated by the server (`<org>/<id>`), but a key is still never allowed to leave the root. */
function localPath(root: string, key: string): string {
  const target = path.resolve(root, key);
  if (target !== root && !target.startsWith(root + path.sep)) throw new Error(`storage key escapes the root: ${key}`);
  return target;
}

function localStorage(dir: string): Storage {
  const root = path.resolve(dir);
  return {
    async put(key, body) {
      const target = localPath(root, key);
      await mkdir(path.dirname(target), { recursive: true });
      await writeFile(target, body);
    },
    get: async (key) => readFile(localPath(root, key)),
    remove: async (key) => rm(localPath(root, key), { force: true }),
  };
}

function s3Storage(config: Config): Storage {
  const client = new S3Client({
    region: config.S3_REGION,
    ...(config.S3_ENDPOINT ? { endpoint: config.S3_ENDPOINT } : {}),
    forcePathStyle: config.S3_FORCE_PATH_STYLE,
    // With no keys given, the SDK's own chain applies (instance role, environment…).
    ...(config.S3_ACCESS_KEY_ID
      ? { credentials: { accessKeyId: config.S3_ACCESS_KEY_ID, secretAccessKey: config.S3_SECRET_ACCESS_KEY } }
      : {}),
  });
  const Bucket = config.S3_BUCKET;
  return {
    put: async (Key, Body, contentType) =>
      void (await client.send(
        new PutObjectCommand({ Bucket, Key, Body, ...(contentType ? { ContentType: contentType } : {}) }),
      )),
    async get(Key) {
      const { Body } = await client.send(new GetObjectCommand({ Bucket, Key }));
      if (!Body) throw new Error(`storage object ${Key} has no body`);
      return Buffer.from(await Body.transformToByteArray());
    },
    remove: async (Key) => void (await client.send(new DeleteObjectCommand({ Bucket, Key }))),
  };
}

export const createStorage = (config: Config): Storage =>
  config.STORAGE_DRIVER === "s3" ? s3Storage(config) : localStorage(config.STORAGE_DIR);
