#!/usr/bin/env node
/**
 * i18n tooling (the Node replacement for valuz-agent's i18n/scripts/*.py).
 *
 *   node scripts/i18n.mjs gen     regenerate packages/shared/src/types/i18n.ts from en-US.json
 *   node scripts/i18n.mjs check   validate every locale against the schema, check that all
 *                                 locales have the same keys, and that the generated types are current
 */
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import Ajv from "ajv/dist/2020.js";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const localesDir = path.join(root, "i18n/locales");
const typesFile = path.join(root, "packages/shared/src/types/i18n.ts");
const REFERENCE = "en-US.json";

const readJson = (file) => JSON.parse(readFileSync(file, "utf8"));

/** Every leaf of a nested locale object as a dot path. */
function dotPaths(value, prefix = "") {
  if (value === null || typeof value !== "object" || Array.isArray(value)) return [];
  return Object.keys(value).flatMap((key) => {
    const full = prefix ? `${prefix}.${key}` : key;
    const child = value[key];
    return child !== null && typeof child === "object" && !Array.isArray(child) ? dotPaths(child, full) : [full];
  });
}

function renderTypes() {
  const keys = dotPaths(readJson(path.join(localesDir, REFERENCE))).sort();
  if (keys.length === 0) throw new Error(`${REFERENCE} has no translation keys`);
  return (
    "// Auto-generated by scripts/i18n.mjs — DO NOT EDIT.\n// Regenerate with: pnpm i18n:gen\n\n" +
    "/** Dot-path translation keys from i18n/locales/en-US.json. */\n" +
    `export type KnownI18nKey =\n${keys.map((k) => `  | "${k}"`).join("\n")};\n\n` +
    "/** Either a known main-app key or a plugin-contributed key.\n" +
    " *  Plugin keys are registered at runtime via\n" +
    " *  ``registerLocaleNamespace`` and never go through codegen. */\n" +
    "export type I18nKey = KnownI18nKey | (string & {});\n"
  );
}

function gen() {
  const content = renderTypes();
  writeFileSync(typesFile, content);
  console.info(
    `generated ${path.relative(root, typesFile)} (${content.split("\n").filter((l) => l.startsWith("  | ")).length} keys)`,
  );
}

function check() {
  const validate = new Ajv({ allErrors: true, strict: false }).compile(readJson(path.join(root, "i18n/schema.json")));
  const files = readdirSync(localesDir)
    .filter((f) => f.endsWith(".json"))
    .sort();
  let failures = 0;
  const reference = new Set(dotPaths(readJson(path.join(localesDir, REFERENCE))));
  for (const file of files) {
    const data = readJson(path.join(localesDir, file));
    if (!validate(data)) {
      failures += 1;
      console.error(`FAIL ${file}: ${validate.errors.map((e) => `${e.instancePath || "/"} ${e.message}`).join("; ")}`);
      continue;
    }
    if (file === REFERENCE) continue;
    const keys = new Set(dotPaths(data));
    const missing = [...reference].filter((k) => !keys.has(k));
    const extra = [...keys].filter((k) => !reference.has(k));
    if (missing.length) console.error(`FAIL ${file}: missing keys: ${missing.join(", ")}`);
    if (extra.length) console.error(`FAIL ${file}: extra keys: ${extra.join(", ")}`);
    if (missing.length || extra.length) failures += 1;
    else console.info(`OK   ${file} (${keys.size} keys match ${REFERENCE})`);
  }
  let current = "";
  try {
    current = readFileSync(typesFile, "utf8");
  } catch {
    // reported below
  }
  if (current !== renderTypes()) {
    failures += 1;
    console.error(`FAIL ${path.relative(root, typesFile)} is out of date — run \`pnpm i18n:gen\` and commit`);
  }
  if (failures) process.exit(1);
  console.info(`\nAll ${files.length} locale(s) valid, consistent, and in sync with the generated types.`);
}

const command = process.argv[2];
if (command === "gen") gen();
else if (command === "check") check();
else {
  console.error("usage: node scripts/i18n.mjs <gen|check>");
  process.exit(2);
}
